[platformio]
src_dir = .

[env:nodemcu-32s]
platform = espressif32 @ 6.12.0
board = nodemcu-32s
framework = arduino
extra_scripts = pre:build_timestamp.py
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = spiroscan_partitions.csv
lib_deps =
    adafruit/Adafruit NeoPixel @ 1.15.2
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ 1.1.2
build_src_filter = +<*> -<tests/> -<.pio/>
